[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ["chat"]

[tool.setuptools.packages.find]
where = ["."]
include = ["tools*"]

[project]
name = "cmc-csci40-MeganTu"
version = "1.0.7"
description = "An LLM in python that chats like a pirate using a GROQ API key and calls tools (calculate, ls, cat, grep)."
readme = "README.md"
authors = [{ name = "Megan Tu", email = "mtu@students.pitzer.edu" }]
requires-python = ">=3.9"
dependencies = [
    "groq",
    "python-dotenv",
]

[project.scripts]
chat = "chat:repl"